### PR TITLE
Zehitomo meetup

### PR DESCRIPTION
**Pull request by beaunus**
@yanarchy We are in the process of developing some algorithms problems for the Meetup on Tuesday, Aug 28. This PR is currently a work-in-progress. We will let you know when we have finished our candidate exercises.

I think that we need 2 more problems in order to satisfy the requirements for the meetup.

Let's try to make 1 more hard problem (level 5) and 1 more (level 2) problem.

### CODE REVIEW

**Comment by yanarchy** [comment]
No problem! @beaunus

**Comment by yanarchy** [comment]
@beaunus My only feedback is that level 5 (needle and haystack) is a bit easier than our usual 5's.

**Comment by yanarchy** [comment]
@beaunus I'll merge for now though.

**Comment by beaunus** [comment]
I'll try to come up with a super hard level 5. Thanks.

**Comment by yanarchy** [comment]
@beaunus Don't worry about it. To make it difficult, I usually just put an impossible constraint on it.

**Pull request merged**
